services:
  prometheus0:
    image: prom/prometheus:v2.9.2
    container_name: prometheus0
    user: root
    volumes:
      - thanos0:/data
      - ./data/local-prometheus-data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/data/prom0"
      - "--log.level=warn"
      - "--web.enable-lifecycle"
      - "--storage.tsdb.min-block-duration=2h"
      - "--storage.tsdb.max-block-duration=2h"
      - "--web.listen-address=0.0.0.0:9090"
    ports:
      - "9090:9090"
    networks:
      - thanos

  node-exporter:
    image: prom/node-exporter:v0.18.1
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - thanos

networks:
  thanos: {}

volumes:
  thanos0: {}
