services:
  minio:
    image: minio/minio:RELEASE.2020-01-03T19-12-21Z
    container_name: minio
    hostname: minio
    volumes:
      - minio:/export
    ports:
      - "9000:9000"
    networks:
      - thanos
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123456
    command: server /export
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  mc:
    image: minio/mc
    container_name: mc
    entrypoint: |
      sh -c 'sh -s << EOF
      mc config host add tmp minio:9000 admin admin123456
      mc mb tmp/thanos
      mc config host rm tmp
      sleep 10000000
      EOF'
    networks:
      - thanos
    depends_on:
      - minio


  prometheus0:
    image: prom/prometheus:v2.9.2
    container_name: prometheus0
    user: root
    volumes:
      - thanos0:/data
      - ./data/local-prometheus-data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/data/prom0"
      - "--log.level=warn"
      - "--web.enable-lifecycle"
      - "--storage.tsdb.min-block-duration=2h"
      - "--storage.tsdb.max-block-duration=2h"
      - "--web.listen-address=0.0.0.0:9090"
    ports:
      - "9090:9090"
    networks:
      - thanos

  node-exporter:
    image: prom/node-exporter:v0.18.1
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - thanos

networks:
  thanos: {}

volumes:
  thanos0: {}
  minio: {}
